version: "3.3"
services: 
  app:
    container_name: app
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    volumes: 
      - ../.:/var/www/app
      - ./app/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./app/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: unless-stopped
    depends_on: 
      - app-db
    networks: 
      - app
  
  app-nginx:
    container_name: app-nginx
    image: nginx:1.19.6-alpine
    depends_on: 
      - app
    volumes:
      - ../.:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks: 
      - app

  app-db:
    container_name: app-db
    image: mysql:8.0.23
    ports: 
      - 3306:3306
    volumes: 
      - dbdata:/var/lib/mysql
    env_file: 
      - ../.env.local
    restart: unless-stopped
    networks: 
      - app

networks: 
  app:
    external: true

volumes:
  dbdata:
    driver: local